executors:
  nbcollection-builder:
    docker:
    - image: continuumio/miniconda3:latest
    resource_class: medium
    working_directory: ~/repo
jobs:
  Jdat Notebooks-Ifu Cube Continuum Fit:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names IFU_cube_continuum_fit
        name: Build Jdat Notebooks-Ifu Cube Continuum Fit notebooks
        no_output_timeout: 60m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Pull Request:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: bash ./.circleci/build-pull-request.sh
        name: Build Pull Request
        no_output_timeout: 60m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
version: 2.1
workflows:
  Build Notebooks:
    jobs:
    - Jdat Notebooks-Ifu Cube Continuum Fit
    - Pull Request
  version: '2.1'
