executors:
  nbcollection-builder:
    docker:
    - image: continuumio/miniconda3:4.10.3
    resource_class: medium
    working_directory: ~/repo
jobs:
  Publish Website:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
        no_output_timeout: 120m
    - run:
        command: nbcollection-ci merge-artifacts -c  -o $CIRCLE_PROJECT_USERNAME -r
          $CIRCLE_PROJECT_REPONAME
        name: Publish Website
        no_output_timeout: 120m
    - add_ssh_keys
    - run:
        command: nbcollection-ci site-deployment -r origin -b gh-pages
        name: Deploy Website
        no_output_timeout: 120m
  Pull Request:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: bash ./.circleci/build-pull-request.sh
        name: Build Pull Request
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
version: 2.1
workflows:
  Build Notebooks:
    jobs:
    - Pull Request
    - Publish Website:
        requires: []
  version: '2.1'
