executors:
  nbcollection-builder:
    docker:
    - image: continuumio/miniconda3:latest
    resource_class: medium
    working_directory: ~/repo
jobs:
  Jdat Notebooks-Aperture Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names aperture_photometry
        name: Build Jdat Notebooks-Aperture Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Asdf Example:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names asdf_example
        name: Build Jdat Notebooks-Asdf Example notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Background Estimation Imaging:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names background_estimation_imaging
        name: Build Jdat Notebooks-Background Estimation Imaging notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Cube Fitting:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names cube_fitting
        name: Build Jdat Notebooks-Cube Fitting notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Ifu Optimal:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names ifu_optimal
        name: Build Jdat Notebooks-Ifu Optimal notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Optimal Extraction:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names optimal_extraction
        name: Build Jdat Notebooks-Optimal Extraction notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Psf Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names psf_photometry
        name: Build Jdat Notebooks-Psf Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Transit Spectroscopy Notebook:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names transit_spectroscopy_notebook
        name: Build Jdat Notebooks-Transit Spectroscopy Notebook notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Publish Website:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
        no_output_timeout: 120m
    - run:
        command: nbcollection-ci merge-artifacts -c jdat_notebooks -o $CIRCLE_PROJECT_USERNAME
          -r $CIRCLE_PROJECT_REPONAME
        name: Publish Website
        no_output_timeout: 120m
    - add_ssh_keys
    - run:
        command: nbcollection-ci site-deployment -r origin -b gh-pages
        name: Deploy Website
        no_output_timeout: 120m
  Pull Request:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: bash ./.circleci/build-pull-request.sh
        name: Build Pull Request
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
version: 2.1
workflows:
  Build Notebooks:
    jobs:
    - Jdat Notebooks-Cube Fitting
    - Jdat Notebooks-Optimal Extraction
    - Jdat Notebooks-Ifu Optimal
    - Jdat Notebooks-Background Estimation Imaging
    - Jdat Notebooks-Psf Photometry
    - Jdat Notebooks-Asdf Example
    - Jdat Notebooks-Aperture Photometry
    - Jdat Notebooks-Transit Spectroscopy Notebook
    - Pull Request
    - Publish Website:
        requires:
        - Jdat Notebooks-Cube Fitting
        - Jdat Notebooks-Optimal Extraction
        - Jdat Notebooks-Ifu Optimal
        - Jdat Notebooks-Background Estimation Imaging
        - Jdat Notebooks-Psf Photometry
        - Jdat Notebooks-Asdf Example
        - Jdat Notebooks-Aperture Photometry
        - Jdat Notebooks-Transit Spectroscopy Notebook
  version: '2.1'
