executors:
  nbcollection-builder:
    docker:
    - image: continuumio/miniconda3:latest
    resource_class: medium
    working_directory: ~/repo
jobs:
  Jdat Notebooks-Aperture Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names aperture_photometry
        name: Build Jdat Notebooks-Aperture Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/aperture_photometry/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/aperture_photometry
        name: Notebook Validation Tests
  Jdat Notebooks-Asdf Example:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names asdf_example
        name: Build Jdat Notebooks-Asdf Example notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/asdf_example/pre-requirements.txt ;
          pip install -r jdat_notebooks/asdf_example/requirements.txt ; python -m
          pytest --nbval  jdat_notebooks/asdf_example
        name: Notebook Validation Tests
  Jdat Notebooks-Background Estimation Imaging:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names background_estimation_imaging
        name: Build Jdat Notebooks-Background Estimation Imaging notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/background_estimation_imaging/pre-requirements.txt
          ; pip install -r jdat_notebooks/background_estimation_imaging/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/background_estimation_imaging
        name: Notebook Validation Tests
  Jdat Notebooks-Cube Fitting:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names cube_fitting
        name: Build Jdat Notebooks-Cube Fitting notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/cube_fitting/requirements.txt ; python
          -m pytest --nbval  jdat_notebooks/cube_fitting
        name: Notebook Validation Tests
  Jdat Notebooks-Ifu Cube Continuum Fit:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names IFU_cube_continuum_fit
        name: Build Jdat Notebooks-Ifu Cube Continuum Fit notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/IFU_cube_continuum_fit/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/IFU_cube_continuum_fit
        name: Notebook Validation Tests
  Jdat Notebooks-Ifu Optimal:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names ifu_optimal
        name: Build Jdat Notebooks-Ifu Optimal notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/ifu_optimal/pre-requirements.txt ;
          pip install -r jdat_notebooks/ifu_optimal/requirements.txt ; python -m pytest
          --nbval  jdat_notebooks/ifu_optimal
        name: Notebook Validation Tests
  Jdat Notebooks-Miri Ifu Ysos In The Lmc:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names MIRI_IFU_YSOs_in_the_LMC
        name: Build Jdat Notebooks-Miri Ifu Ysos In The Lmc notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/MIRI_IFU_YSOs_in_the_LMC/pre-requirements.txt
          ; pip install -r jdat_notebooks/MIRI_IFU_YSOs_in_the_LMC/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/MIRI_IFU_YSOs_in_the_LMC
        name: Notebook Validation Tests
  Jdat Notebooks-Miri Lrs Spectral Extraction:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names MIRI_LRS_spectral_extraction
        name: Build Jdat Notebooks-Miri Lrs Spectral Extraction notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/MIRI_LRS_spectral_extraction/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/MIRI_LRS_spectral_extraction
        name: Notebook Validation Tests
  Jdat Notebooks-Mos-Spectroscopy:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names mos-spectroscopy
        name: Build Jdat Notebooks-Mos-Spectroscopy notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/mos-spectroscopy/requirements.txt ;
          python -m pytest --nbval  jdat_notebooks/mos-spectroscopy
        name: Notebook Validation Tests
  Jdat Notebooks-Mrs Mstar Analysis:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names MRS_Mstar_analysis
        name: Build Jdat Notebooks-Mrs Mstar Analysis notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/MRS_Mstar_analysis/pre-requirements.txt
          ; pip install -r jdat_notebooks/MRS_Mstar_analysis/requirements.txt ; python
          -m pytest --nbval  jdat_notebooks/MRS_Mstar_analysis
        name: Notebook Validation Tests
  Jdat Notebooks-Nircam Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names NIRCam_photometry
        name: Build Jdat Notebooks-Nircam Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/NIRCam_photometry/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/NIRCam_photometry
        name: Notebook Validation Tests
  Jdat Notebooks-Nircam Psf-Matched Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names NIRCam_PSF-matched_photometry
        name: Build Jdat Notebooks-Nircam Psf-Matched Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/NIRCam_PSF-matched_photometry/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/NIRCam_PSF-matched_photometry
        name: Notebook Validation Tests
  Jdat Notebooks-Niriss Wfss Postpipeline:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names NIRISS_WFSS_postpipeline
        name: Build Jdat Notebooks-Niriss Wfss Postpipeline notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/NIRISS_WFSS_postpipeline/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/NIRISS_WFSS_postpipeline
        name: Notebook Validation Tests
  Jdat Notebooks-Nirspec Mast Query:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names NIRSpec_MAST_Query
        name: Build Jdat Notebooks-Nirspec Mast Query notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/NIRSpec_MAST_Query/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/NIRSpec_MAST_Query
        name: Notebook Validation Tests
  Jdat Notebooks-Optimal Extraction:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names optimal_extraction
        name: Build Jdat Notebooks-Optimal Extraction notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/optimal_extraction/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/optimal_extraction
        name: Notebook Validation Tests
  Jdat Notebooks-Psf Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names psf_photometry
        name: Build Jdat Notebooks-Psf Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/psf_photometry/requirements.txt ; python
          -m pytest --nbval  jdat_notebooks/psf_photometry
        name: Notebook Validation Tests
  Jdat Notebooks-Specviz Notebookgui Interaction:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names specviz_notebookGUI_interaction
        name: Build Jdat Notebooks-Specviz Notebookgui Interaction notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/specviz_notebookGUI_interaction/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/specviz_notebookGUI_interaction
        name: Notebook Validation Tests
  Jdat Notebooks-Transit Spectroscopy Notebook:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names transit_spectroscopy_notebook
        name: Build Jdat Notebooks-Transit Spectroscopy Notebook notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
    - run:
        command: pip install -r jdat_notebooks/transit_spectroscopy_notebook/requirements.txt
          ; python -m pytest --nbval  jdat_notebooks/transit_spectroscopy_notebook
        name: Notebook Validation Tests
  Publish Website:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
        no_output_timeout: 120m
    - run:
        command: nbcollection-ci merge-artifacts -c jdat_notebooks -o $CIRCLE_PROJECT_USERNAME
          -r $CIRCLE_PROJECT_REPONAME
        name: Publish Website
        no_output_timeout: 120m
    - add_ssh_keys
    - run:
        command: nbcollection-ci site-deployment -r origin -b gh-pages
        name: Deploy Website
        no_output_timeout: 120m
  Pull Request:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: bash ./.circleci/build-pull-request.sh
        name: Build Pull Request
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
version: 2.1
workflows:
  Build Notebooks:
    jobs:
    - Jdat Notebooks-Niriss Wfss Postpipeline
    - Jdat Notebooks-Mos-Spectroscopy
    - Jdat Notebooks-Mrs Mstar Analysis
    - Jdat Notebooks-Cube Fitting
    - Jdat Notebooks-Ifu Cube Continuum Fit
    - Jdat Notebooks-Nircam Psf-Matched Photometry
    - Jdat Notebooks-Miri Ifu Ysos In The Lmc
    - Jdat Notebooks-Optimal Extraction
    - Jdat Notebooks-Ifu Optimal
    - Jdat Notebooks-Background Estimation Imaging
    - Jdat Notebooks-Psf Photometry
    - Jdat Notebooks-Specviz Notebookgui Interaction
    - Jdat Notebooks-Asdf Example
    - Jdat Notebooks-Aperture Photometry
    - Jdat Notebooks-Nirspec Mast Query
    - Jdat Notebooks-Miri Lrs Spectral Extraction
    - Jdat Notebooks-Transit Spectroscopy Notebook
    - Jdat Notebooks-Nircam Photometry
    - Pull Request
    - Publish Website:
        requires:
        - Jdat Notebooks-Niriss Wfss Postpipeline
        - Jdat Notebooks-Mos-Spectroscopy
        - Jdat Notebooks-Mrs Mstar Analysis
        - Jdat Notebooks-Cube Fitting
        - Jdat Notebooks-Ifu Cube Continuum Fit
        - Jdat Notebooks-Nircam Psf-Matched Photometry
        - Jdat Notebooks-Miri Ifu Ysos In The Lmc
        - Jdat Notebooks-Optimal Extraction
        - Jdat Notebooks-Ifu Optimal
        - Jdat Notebooks-Background Estimation Imaging
        - Jdat Notebooks-Psf Photometry
        - Jdat Notebooks-Specviz Notebookgui Interaction
        - Jdat Notebooks-Asdf Example
        - Jdat Notebooks-Aperture Photometry
        - Jdat Notebooks-Nirspec Mast Query
        - Jdat Notebooks-Miri Lrs Spectral Extraction
        - Jdat Notebooks-Transit Spectroscopy Notebook
        - Jdat Notebooks-Nircam Photometry
  version: '2.1'
