executors:
  nbcollection-builder:
    docker:
<<<<<<< HEAD
    - image: continuumio/miniconda3:4.10.3
=======
        - image: python:3.7-slim-buster
>>>>>>> be1b0055c9b7a28b2e3ad3f58605de8003666bab
    resource_class: medium
    working_directory: ~/repo
jobs:
  Jdat Notebooks-Asdf Example:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names asdf_example
        name: Build Jdat Notebooks-Asdf Example notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Background Estimation Imaging:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names background_estimation_imaging
        name: Build Jdat Notebooks-Background Estimation Imaging notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Ifu Optimal:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names ifu_optimal
        name: Build Jdat Notebooks-Ifu Optimal notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
<<<<<<< HEAD
  Jdat Notebooks-Miri Ifu Ysos In The Lmc:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names MIRI_IFU_YSOs_in_the_LMC
        name: Build Jdat Notebooks-Miri Ifu Ysos In The Lmc notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Miri Lrs Spectral Extraction:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names MIRI_LRS_spectral_extraction
        name: Build Jdat Notebooks-Miri Lrs Spectral Extraction notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Mos-Spectroscopy:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names mos-spectroscopy
        name: Build Jdat Notebooks-Mos-Spectroscopy notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Mrs Mstar Analysis:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names MRS_Mstar_analysis
        name: Build Jdat Notebooks-Mrs Mstar Analysis notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Nircam Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names NIRCam_photometry
        name: Build Jdat Notebooks-Nircam Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Nircam Psf-Matched Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names NIRCam_PSF-matched_photometry
        name: Build Jdat Notebooks-Nircam Psf-Matched Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Niriss Wfss Postpipeline:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names NIRISS_WFSS_postpipeline
        name: Build Jdat Notebooks-Niriss Wfss Postpipeline notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Nirspec Mast Query:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names NIRSpec_MAST_Query
        name: Build Jdat Notebooks-Nirspec Mast Query notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Optimal Extraction:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names optimal_extraction
        name: Build Jdat Notebooks-Optimal Extraction notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Optimal Extraction Dynamic:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names optimal_extraction_dynamic
        name: Build Jdat Notebooks-Optimal Extraction Dynamic notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Psf Photometry:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names psf_photometry
        name: Build Jdat Notebooks-Psf Photometry notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Specviz Notebookgui Interaction:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names specviz_notebookGUI_interaction
        name: Build Jdat Notebooks-Specviz Notebookgui Interaction notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
  Jdat Notebooks-Transit Spectroscopy Notebook:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: nbcollection-ci build-notebooks --collection-names jdat_notebooks
          --category-names transit_spectroscopy_notebook
        name: Build Jdat Notebooks-Transit Spectroscopy Notebook notebooks
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
=======
>>>>>>> be1b0055c9b7a28b2e3ad3f58605de8003666bab
  Publish Website:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
        no_output_timeout: 120m
    - run:
        command: nbcollection-ci merge-artifacts -c jdat_notebooks -o $CIRCLE_PROJECT_USERNAME
          -r $CIRCLE_PROJECT_REPONAME
        name: Publish Website
        no_output_timeout: 120m
    - add_ssh_keys
    - run:
        command: nbcollection-ci site-deployment -r origin -b gh-pages
        name: Deploy Website
        no_output_timeout: 120m
  Pull Request:
    executor: nbcollection-builder
    steps:
    - checkout
    - run:
        command: bash ./.circleci/setup-env.sh
        name: Setup Environment
    - run:
        command: bash ./.circleci/build-pull-request.sh
        name: Build Pull Request
        no_output_timeout: 120m
    - store_artifacts:
        path: /tmp/nbcollection-ci-artifacts
version: 2.1
workflows:
  Build Notebooks:
    jobs:
    - Jdat Notebooks-Ifu Optimal
    - Jdat Notebooks-Background Estimation Imaging
    - Jdat Notebooks-Asdf Example
<<<<<<< HEAD
    - Jdat Notebooks-Aperture Photometry
    - Jdat Notebooks-Nirspec Mast Query
    - Jdat Notebooks-Miri Lrs Spectral Extraction
    - Jdat Notebooks-Transit Spectroscopy Notebook
    - Jdat Notebooks-Nircam Photometry
    - Jdat Notebooks-Optimal Extraction Dynamic
=======
>>>>>>> be1b0055c9b7a28b2e3ad3f58605de8003666bab
    - Pull Request
    - Publish Website:
        requires:
        - Jdat Notebooks-Ifu Optimal
        - Jdat Notebooks-Background Estimation Imaging
        - Jdat Notebooks-Asdf Example
<<<<<<< HEAD
        - Jdat Notebooks-Aperture Photometry
        - Jdat Notebooks-Nirspec Mast Query
        - Jdat Notebooks-Miri Lrs Spectral Extraction
        - Jdat Notebooks-Transit Spectroscopy Notebook
        - Jdat Notebooks-Nircam Photometry
        - Jdat Notebooks-Optimal Extraction Dynamic
=======
>>>>>>> be1b0055c9b7a28b2e3ad3f58605de8003666bab
  version: '2.1'
